services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data


  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow-secure
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:admin123@postgres/postgres
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./transformations:/opt/airflow
    ports:
      - "8080:8080"
    command: ["airflow", "webserver"]
    restart: always

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow-secure
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:admin123@postgres/postgres
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./transformations:/opt/airflow
    command: ["airflow", "scheduler"]
    restart: always

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow-secure
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:admin123@postgres/postgres
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./transformations:/opt/airflow
    entrypoint: >
      bash -c "
      echo 'Waiting for Postgres...' &&
      while ! pg_isready -h postgres -p 5432; do sleep 1; done &&
      airflow db upgrade &&
      airflow users create --username admin --password admin --firstname Camila --lastname Muñoz --role Admin --email admin@example.com"
    restart: "no"

volumes:
  postgres_data: